version: '3.5'

services:
  airprint:
    container_name: airprint
    image: znetwork/synology-airprint:latest
    build: .
    restart: always
    network_mode: "host"
    environment:
      CUPSADMIN: admin
      CUPSPASSWORD: admin
    volumes:
      - /volume1/docker/synology-airprint/services:/services
      - /volume1/docker/synology-airprint/config:/config
      - /var/run/dbus:/var/run/dbus
