name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu:jammy

    steps:
    - name: Check out the repo
      uses: actions/checkout

    - name: Login to dockerhub
      uses: docker/login-action
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action
      with:
       context:
       push: true
       tags: bekdan1988/githubaction:latest
